[package]
name = "slam"
version = "0.1.0"
edition = "2021"
description = "An ELO-based matchmaking system for multiplayer games"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
